services:
  palworld-casual:
    image: ghcr.io/netwarlan/palworld
    environment:
      PALWORLD_SERVER_NAME: "NETWAR Palworld"
      PALWORLD_SERVER_UPDATE_ON_START: true
      PALWORLD_SERVER_DIFFICULTY: "Casual"
      PALWORLD_SERVER_MULTIPLAY: "True"
      PALWORLD_SERVER_PVP: "False"
      PALWORLD_SERVER_SELECT_START_LOCATION: "False"
      PALWORLD_SERVER_COOP_PLAYER_MAX: "4"
      PALWORLD_SERVER_MAX_PLAYERS: "64"
      PALWORLD_SERVER_DESCRIPTION: "GOTTA SHOOT THEM ALL!"
      PALWORLD_SERVER_ADMIN_PASSWORD: "heatshot"
      PALWORLD_SERVER_PORT: "8211"
      PALWORLD_SERVER_RCON_ENABLE: "True"
      PALWORLD_SERVER_RCON_PORT: "25575"
    volumes:
      - ./data:/app/palworld
    restart: "unless-stopped"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.126

networks:
  vlan:
    external: true
