version: "3"

services:
  cs2-scrim-1:
    image: ghcr.io/netwarlan/cs2
    environment:
      CS2_SERVER_PORT: 27015
      CS2_SERVER_MAXPLAYERS: 24
      CS2_SERVER_MAP: "de_nuke"
      CS2_SERVER_SVLAN: 1
      CS2_SERVER_HOSTNAME: "NETWAR CS2 - SCRIM 1"
      CS2_SERVER_UPDATE_ON_START: true
      CS2_SERVER_VALIDATE_ON_START: false
      CS2_SERVER_RCONPW: "headshot"
      CS2_SERVER_GAME_MODE_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/cs2/gamemodes_server.txt"
      CS2_SERVER_GAME_TYPE: 0
      CS2_SERVER_GAME_MODE: 1
      CS2_SERVER_MAPGROUP: "nw_competitive"
      CS2_SERVER_GOTV_ENABLE: 0
      CS2_SERVER_ENABLE_REMOTE_CFG: true
      CS2_SERVER_REMOTE_CFG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/cs2/5v5_competitive.cfg"
    volumes:
      - ./data:/app/cs2
    restart: "unless-stopped"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.136

  cs2-scrim-2:
    image: ghcr.io/netwarlan/cs2
    environment:
      CS2_SERVER_PORT: 27015
      CS2_SERVER_MAXPLAYERS: 24
      CS2_SERVER_MAP: "de_inferno"
      CS2_SERVER_SVLAN: 1
      CS2_SERVER_HOSTNAME: "NETWAR CS2 - SCRIM 2"
      CS2_SERVER_RCONPW: "headshot"
      CS2_SERVER_UPDATE_ON_START: false
      CS2_SERVER_VALIDATE_ON_START: false
      CS2_SERVER_GAME_MODE_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/cs2/gamemodes_server.txt"
      CS2_SERVER_GAME_TYPE: 0
      CS2_SERVER_GAME_MODE: 1
      CS2_SERVER_MAPGROUP: "nw_armsrace"
      CS2_SERVER_GOTV_ENABLE: 0
      CS2_SERVER_ENABLE_REMOTE_CFG: true
      CS2_SERVER_REMOTE_CFG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/cs2/5v5_competitive.cfg"
    volumes:
      - ./data:/app/cs2
    restart: "unless-stopped"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.137

networks:
  vlan:
    external: true
