version: "3"

services:
  rust:
    image: ghcr.io/netwarlan/rust
    volumes:
      - ./data:/app/rust
    restart: "unless-stopped"
    environment:
      RUST_SERVER_NAME: "NETWAR RUST"
      RUST_SERVER_DESCRIPTION: "plz behave"
      RUST_SERVER_SEED: "321699587"
      RUST_SERVER_WORLDSIZE: "3000"
      RUST_SERVER_WIPE_ALL: false
      RUST_UMOD_ENABLED: true
      RUST_SERVER_UPDATE_ON_START: true
      RUST_UMOD_BLUEPRINT_MANAGER: true
      RUST_UMOD_GATHER_MANAGER: true
      RUST_UMOD_NO_WORKBENCHES: true
      RUST_UMOD_BLUEPRINT_MANAGER_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/BlueprintManager.json"
      RUST_UMOD_GATHER_MANAGER_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/GatherManager.json"
      RUST_UMOD_NO_WORKBENCHES_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/NoWorkbench.json"
      RUST_SERVER_USERS_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/users.cfg"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.127

networks:
  vlan:
    external: true