services:
  rust:
    image: ghcr.io/netwarlan/rust
    volumes:
      - ./data:/app/rust
    restart: "unless-stopped"
    environment:
      RUST_RCON_ENABLE: true
      RUST_RCON_PORT: "28016"
      RUST_SERVER_DESCRIPTION: "NETWAR is a 501(c)(3) non-profit volunteer organization dedicated to hosting LAN parties"
      RUST_SERVER_HEADER_IMAGE: "https://www.netwar.org/wp-content/uploads/2018/01/Netwar_Logo.png"
      RUST_SERVER_MAXPLAYERS: "75"
      RUST_SERVER_NAME: "RUSTY NETWAR"
      RUST_SERVER_SEED: "88028464"
      RUST_SERVER_UPDATE_ON_START: true
      RUST_SERVER_VALIDATE_ON_START: false
      RUST_SERVER_URL: "https://www.netwar.org"
      RUST_SERVER_USERS_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/users.cfg"
      RUST_SERVER_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/server.cfg"
      RUST_SERVER_WIPE_ALL: false
      RUST_SERVER_WORLDSIZE: "3700"
      RUST_UMOD_BLUEPRINT_MANAGER: true
      RUST_UMOD_BLUEPRINT_MANAGER_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/BlueprintManager.json"
      RUST_UMOD_ENABLED: true
      RUST_UMOD_GATHER_MANAGER: true
      RUST_UMOD_GATHER_MANAGER_CONFIG: "https://raw.githubusercontent.com/netwarlan/server-configs/main/rust/GatherManager.json"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.127
    cpuset: "7-11"

networks:
  vlan:
    external: true