version: "3"

services:
  gmod:
    image: ghcr.io/netwarlan/garrysmod
    volumes:
      - ./data:/app/gmod
    environment:
      GMOD_SERVER_HOSTNAME: "NETWAR Prophunt?"
      GMOD_SERVER_MAP: "ph_office"
      GMOD_SERVER_UPDATE_ON_START: true
    restart: "unless-stopped"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      vlan:
        ipv4_address: 10.10.10.123

networks:
  vlan:
    external: true